// Strips conditional sections out of the analysis system prompt before
// it's sent to the LLM. Sections in prompt.md are tagged with
// `<!--:if KEY-->...<!--:endif-->` markers; the assembler removes blocks
// whose condition isn't satisfied by the current investigation.
//
// Two flavors of condition:
//   1. Input-shape: google_harvest / passive_harvest / hidden_profile /
//      avatar — derived from the ProfileSummary.
//   2. Per-factor: `factor=<key>` blocks describe how the LLM should
//      score a given factor. When the factor is computed deterministically
//      in TS (see `deterministic_factors.ts`), the block is removed and
//      the LLM scores only the remaining factors.
//
// The required-factor-keys list in prompt.md is wrapped in
// `<!--:factor-list-->...<!--:end-factor-list-->` and is regenerated by
// this module from `llmFactorKeys` so the count word and numbering stay
// consistent with what the LLM is asked to produce.

import { FACTORS } from "../../factors.ts";
import type { ProfileSummary } from "../../types.ts";

// `llmFactorKeys` is the set of factor keys the LLM should score. Factors
// NOT in this set have their section removed from the prompt and are
// expected to be computed deterministically by the caller.
//
// `stripInputConditional` controls whether google_harvest /
// passive_harvest / hidden_profile / avatar blocks are stripped based on
// what's present in the summary. Defaults to true. Set false to keep the
// prompt shape constant across users — useful when you want the
// Anthropic prompt cache to hit reliably across investigations of
// different accounts (each per-user-shaped prompt is a separate cache
// slot, which can outweigh the input-token savings on bursty workloads).
export interface PromptAssemblyOptions {
  llmFactorKeys: readonly string[];
  stripInputConditional?: boolean;
}

interface SectionConditions {
  google_harvest: boolean;
  passive_harvest: boolean;
  hidden_profile: boolean;
  avatar: boolean;
}

export function assemblePrompt(
  rawPrompt: string,
  summary: ProfileSummary,
  options: PromptAssemblyOptions
): string {
  const stripInputConditional = options.stripInputConditional ?? true;

  // When input-conditional stripping is off, treat every input-shape
  // condition as `true` so all blocks are kept — this keeps the prompt
  // shape constant across users (the only remaining variation comes
  // from `stripFactorBlocks`, which is a function of the deployment, not
  // of the user).
  const conditions = stripInputConditional
    ? deriveConditions(summary)
    : keepAllConditions();

  let prompt = stripInputConditionalBlocks(rawPrompt, conditions);
  prompt = stripFactorBlocks(prompt, options.llmFactorKeys);
  prompt = regenerateFactorList(prompt, options.llmFactorKeys);
  return prompt;
}

function keepAllConditions(): SectionConditions {
  return {
    google_harvest: true,
    passive_harvest: true,
    hidden_profile: true,
    avatar: true,
  };
}

function deriveConditions(summary: ProfileSummary): SectionConditions {
  const googleHarvest = summary.google_harvest != null;
  const passiveHarvest = summary.passive_harvest != null;
  const totalKarma = summary.account.total_karma ?? 0;
  const visibleItems =
    summary.activity.posts_fetched + summary.activity.comments_fetched;
  const hiddenProfile = visibleItems <= 5 && totalKarma >= 1000;
  const avatar = summary.avatar.customized === true;

  return {
    google_harvest: googleHarvest,
    passive_harvest: passiveHarvest,
    hidden_profile: hiddenProfile,
    avatar,
  };
}

// Generic block stripper: removes <!--:if KEY-->...<!--:endif--> blocks
// when the predicate returns false for KEY. Leaves the block (including
// the markers, which are HTML comments and invisible to the LLM
// regardless) when the predicate returns true.
function stripBlocks(
  source: string,
  ifPattern: RegExp,
  shouldKeep: (key: string) => boolean
): string {
  // Tokenize on the if/endif markers so we never run a regex across the
  // whole file body (which can be expensive and hard to make non-greedy
  // correctly across newlines).
  const parts: string[] = [];
  let cursor = 0;

  while (cursor < source.length) {
    ifPattern.lastIndex = cursor;
    const match = ifPattern.exec(source);
    if (!match) {
      parts.push(source.slice(cursor));
      break;
    }

    parts.push(source.slice(cursor, match.index));

    const key = match[1];
    const blockStart = match.index + match[0].length;
    const endMarker = "<!--:endif-->";
    const blockEnd = source.indexOf(endMarker, blockStart);
    if (blockEnd === -1) {
      throw new Error(`Unterminated <!--:if ${key}--> block in prompt`);
    }

    if (shouldKeep(key)) {
      parts.push(source.slice(blockStart, blockEnd));
    }

    cursor = blockEnd + endMarker.length;
  }

  return parts.join("");
}

function stripInputConditionalBlocks(
  source: string,
  conditions: SectionConditions
): string {
  // <!--:if web_search-->, etc. (does not match "factor=" form)
  const pattern = /<!--:if ([a-z_]+)-->/g;
  return stripBlocks(source, pattern, (key) => {
    if (!(key in conditions)) {
      throw new Error(`Unknown input-conditional key in prompt: ${key}`);
    }

    return conditions[key as keyof SectionConditions];
  });
}

function stripFactorBlocks(
  source: string,
  llmFactorKeys: readonly string[]
): string {
  const factorSet = new Set(llmFactorKeys);

  // <!--:if factor=username_pattern-->, etc.
  const pattern = /<!--:if factor=([a-z_]+)-->/g;
  return stripBlocks(source, pattern, (key) => factorSet.has(key));
}

// Replace the <!--:factor-list-->...<!--:end-factor-list--> block with a
// freshly numbered list of just the LLM-scored factors. The numeric
// labels (e.g. "1.") are renumbered from 1 so they don't have gaps when
// some factors are stripped.
function regenerateFactorList(
  source: string,
  llmFactorKeys: readonly string[]
): string {
  const startMarker = "<!--:factor-list-->";
  const endMarker = "<!--:end-factor-list-->";
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  if (start === -1 || end === -1) {
    throw new Error("Missing <!--:factor-list--> markers in prompt");
  }

  const orderedKeys = FACTORS.map((f) => f.key).filter((k) =>
    llmFactorKeys.includes(k)
  );
  const count = orderedKeys.length;
  const numberWord = numberToWord(count);
  const lines = orderedKeys.map((key, idx) => `${idx + 1}. \`${key}\``);
  const replacement =
    `Return **exactly these ${numberWord} factors**, in this order, even if a factor shows no signal (use \`score: 0.0\`, low confidence, and a note in \`reasoning\` that nothing notable was observed):\n\n` +
    lines.join("\n");

  return (
    source.slice(0, start) + replacement + source.slice(end + endMarker.length)
  );
}

function numberToWord(n: number): string {
  const words: Record<number, string> = {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
    13: "thirteen",
    14: "fourteen",
    15: "fifteen",
    16: "sixteen",
  };

  return words[n] ?? String(n);
}
